version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Poc.Order.Api/Dockerfile
    container_name: poc_order_api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      MongoDb__ConnectionString: "mongodb://root:root123@mongo:27017/?authSource=admin"
      MongoDb__Database: "PocOrder"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    command: ["--bind_ip_all"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:root123@mongo:27017/?authSource=admin"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root123
    depends_on:
      - mongo

volumes:
  mongo_data:
